#! /bin/bash

# Can add extra reload steps in /usr/local/sbin/acme-reload-extra
[ -x /usr/local/sbin/acme-reload-extra ] && source /usr/local/sbin/acme-reload-extra

# Reload any webserver if active
for s in nginx apache2 haproxy; do
    if systemctl is-active $s >/dev/null; then
        echo "[$(date)] Reloading $s"
        systemctl reload $s
    fi
done
