#! /bin/bash

# Can add extra reload steps in /etc/acme/acme-reload-extra
[ -x /etc/acme/acme-reload-extra ] && source /etc/acme/acme-reload-extra

# Reload any webserver if active
for s in nginx apache2 haproxy; do
    if systemctl is-active $s >/dev/null; then
        logger -t acme-reload <<< "Reloading $s"
        systemctl reload $s
    fi
done
