#!/bin/bash

set -e

acmesh_version="3.1.1"


if [ $# -lt 1 ]; then
  echo "Usage: $0 DEBIAN_BUILD [DIST ...]" >&2
  exit 1
fi
BUILD="$1"

shift 1
DISTROS="$*"
if [ "$DISTROS" = "" ]; then
  DISTROS="jessie stretch buster bullseye bookworm trixie"
fi
declare -A release_versions
release_versions["jessie"]="8"
release_versions["stretch"]="9"
release_versions["buster"]="10"
release_versions["bullseye"]="11"
release_versions["bookworm"]="12"
release_versions["trixie"]="13"

for dist in $DISTROS; do

  # Generate distro-specific changelog
  dch -b -v "$acmesh_version+deb${release_versions[$dist]}+bear${BUILD}" "Debian package automated build"
  sed -i -e "1 s/UNRELEASED/$dist-bearstech/" debian/changelog

  bear-build $dist amd64

  # and reset our debian env for next distro
  git checkout debian/changelog

done
